# E9g 50k: feature_dim=16, 4x256, mlp_lr=1e-3, feature_lr=0.04
_parent_: projects/Bspline-Neus/configs/dtu_scan24_thb_v3_color_mlp_v12_short.yaml

max_iter: 50000

model:
    object:
        bspline:
            hierarchical:
                max_levels: 4
                refine_iters: [10000, 30000, 70000, 150000]

optim:
    sched:
        warm_up_end: 5000
        two_steps: [300000, 400000]

validation_iter: 50000
