#!/usr/bin/env bash
# Batch-run all 8 blender (NeRF-synthetic) scenes: convert -> config -> train -> eval.
# Template config: stage_search/Y14_lego_500k.yaml (validated on lego).
# Held-out: the blender test split (200 views, never trained).
#
# Usage (single GPU):
#   bash projects/Bspline-Neus/scripts/blender_batch.sh
# Usage (multi-GPU server, one scene per GPU):
#   bash projects/Bspline-Neus/scripts/blender_batch.sh --gpus 0,1,2,3
set -e

SCENES="chair drums ficus hotdog lego materials mic ship"
GPUS=""
MAX_ITER=500000   # Y14 evidence: on 100-view blender scenes 150-300k is the
                  # sweet spot; keep 500k for DTU-parity or pass e.g. 300000.

while [ $# -gt 0 ]; do
    case "$1" in
        --gpus) GPUS="$2"; shift 2;;
        --max_iter) MAX_ITER="$2"; shift 2;;
        *) echo "unknown arg $1"; exit 1;;
    esac
done

for SCENE in $SCENES; do
    DATA=datasets/nerf_synthetic/$SCENE
    TRAIN_CFG=projects/Bspline-Neus/configs/blender_batch/${SCENE}.yaml
    HELD_CFG=projects/Bspline-Neus/configs/blender_batch/${SCENE}_heldout.yaml
    LOGDIR=logs/B_${SCENE}_${MAX_ITER}

    # 1) convert (idempotent)
    python projects/Bspline-Neus/scripts/blender_to_json.py --scene $DATA

    # 2) configs from the validated lego template
    mkdir -p projects/Bspline-Neus/configs/blender_batch
    cat > $TRAIN_CFG <<EOF
# Auto-generated by blender_batch.sh
_parent_: projects/Bspline-Neus/configs/stage_search/Y14_lego_500k.yaml

data:
    root: $DATA

max_iter: $MAX_ITER
EOF
    cat > $HELD_CFG <<EOF
# Auto-generated by blender_batch.sh
_parent_: projects/Bspline-Neus/configs/blender_batch/${SCENE}.yaml

data:
    root: ${DATA}_heldout
    val:
        subset: 25
EOF

    echo "== $SCENE: config ready -> $TRAIN_CFG"
done

# 3) train + eval (sequential on one GPU, or fanned out with --gpus)
run_scene() {
    SCENE=$1; GPU=$2
    TRAIN_CFG=projects/Bspline-Neus/configs/blender_batch/${SCENE}.yaml
    HELD_CFG=projects/Bspline-Neus/configs/blender_batch/${SCENE}_heldout.yaml
    LOGDIR=logs/B_${SCENE}_${MAX_ITER}
    CKPT=$LOGDIR/epoch_*_iteration_$(printf %09d $MAX_ITER)_checkpoint.pt

    CUDA_VISIBLE_DEVICES=$GPU python train.py --config $TRAIN_CFG \
        --logdir $LOGDIR --single_gpu > $LOGDIR.log 2>&1
    CKPT=$(ls $CKPT | tail -1)
    CUDA_VISIBLE_DEVICES=$GPU python projects/Bspline-Neus/scripts/eval_psnr.py \
        --single_gpu --config $TRAIN_CFG --checkpoint $CKPT > ${LOGDIR}_eval.out 2>&1
    CUDA_VISIBLE_DEVICES=$GPU python projects/Bspline-Neus/scripts/eval_psnr.py \
        --single_gpu --config $HELD_CFG --checkpoint $CKPT > ${LOGDIR}_heldout_eval.out 2>&1
    grep -a PSNR ${LOGDIR}_eval.out ${LOGDIR}_heldout_eval.out
    cd $LOGDIR && ls *.pt | grep -v "$(printf %09d $MAX_ITER)" | xargs rm -f; cd - > /dev/null
    echo "== $SCENE done"
}

if [ -z "$GPUS" ]; then
    for SCENE in $SCENES; do run_scene $SCENE ""; done
else
    IFS=',' read -ra GPU_ARR <<< "$GPUS"
    N=${#GPU_ARR[@]}
    i=0
    for SCENE in $SCENES; do
        run_scene $SCENE ${GPU_ARR[$((i % N))]} &
        i=$((i + 1))
        if [ $((i % N)) -eq 0 ]; then wait; fi
    done
    wait
fi
echo "ALL SCENES DONE"
